### ISSUE TITLE
Still RuntimeError: Failed to read the record. But I can provide details how TFRecord is generated

### ISSUE THREAD

**Issue by RorschachChen** [vahidk/tfrecord#18]
Traceback (most recent call last):
  File "torchRead.py", line 11, in <module>
    data = next(temp)
  File "/home/cym/anaconda3/envs/tfread/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/cym/anaconda3/envs/tfread/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/cym/anaconda3/envs/tfread/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch
    data.append(next(self.dataset_iter))
  File "/home/cym/anaconda3/envs/tfread/lib/python3.6/site-packages/tfrecord/reader.py", line 86, in tfrecord_loader
    for record in record_iterator:
  File "/home/cym/anaconda3/envs/tfread/lib/python3.6/site-packages/tfrecord/reader.py", line 53, in tfrecord_iterator
    yield from read_records()
  File "/home/cym/anaconda3/envs/tfread/lib/python3.6/site-packages/tfrecord/reader.py", line 47, in read_records
    raise RuntimeError("Failed to read the record.")
RuntimeError: Failed to read the record.

Here is the definition of _float_feature
def _float_feature(value): # used
  return tf.train.Feature(float_list=tf.train.FloatList(value=list(value)))
example = tf.train.Example(features=tf.train.Features(
        feature={
            "ori_image": _float_feature(image.reshape(-1)),
            "aug_image": _float_feature(aug_image.reshape(-1)),
        }))

Using this config I can read out the file with TensorFlow
aug_record_spec = {
          "ori_image": tf.FixedLenFeature([224 * 224 * 3], tf.float32),
          "aug_image": tf.FixedLenFeature([224 * 224 * 3], tf.float32),
      }

I know the problem is raised with 
file.readinto(datum_bytes_view) != length
I also print out the two value:
first is 1204282 = 2 * 602141 cannot be decomposed any more. 
the second is 1048576 = 2^20

 Hope you will notice this, thanks very much~~

**Comment by vahidk** [comment]
Can you try the latest version (1.9)?
