### ISSUE TITLE
MultiTFRecordDataset keeps iterating though dataset(s)

### ISSUE THREAD

**Issue by ayushkarnawat** [vahidk/tfrecord#26]
If we try to iterate though multiple datasets at the same time using torch's `DataLoader`,

```python
import os
import numpy as np
import torch.utils.data

import tfrecord
import tfrecord.torch.dataset
from tfrecord.tools import tfrecord2idx


# Create tmp dir for saving file(s)
rootdir = "tmp/"
if not os.path.isdir(rootdir):
    os.makedirs(rootdir)

# Create and write records to file(s)
data_pattern = os.path.join(rootdir, "dataset{}.tfrecord")
index_pattern = os.path.join(rootdir, "dataset{}.index")
for i in range(2):
    data_path = data_pattern.format(i)
    writer = tfrecord.TFRecordWriter(data_path)
    for idx in range(50):
        writer.write({
            "image": (np.random.bytes(20), "byte"),
            "label": ((np.random.rand(1)*(10**i)).tolist(), "float"),
            "index": ([idx], "int")
        })
    writer.close()

    # Create index
    tfrecord2idx.create_index(data_path, index_pattern.format(i))

splits = {"0": 0.8, "1": 0.2}
description = {"image": "byte", "label": "float"}
dataset = tfrecord.torch.dataset.MultiTFRecordDataset(data_pattern,
    index_pattern=index_pattern, splits=splits, description=description)

loader = torch.utils.data.DataLoader(dataset, batch_size=10)
# data = next(iter(loader))
# print(data["label"])

for idx, batch in enumerate(loader):
    print(idx, [arr.size() for arr in batch.values()])
```

## Current behavior

```
43 [torch.Size([10, 20]), torch.Size([10, 1])]
44 [torch.Size([10, 20]), torch.Size([10, 1])]
45 [torch.Size([10, 20]), torch.Size([10, 1])]
46 [torch.Size([10, 20]), torch.Size([10, 1])]
47 [torch.Size([10, 20]), torch.Size([10, 1])]
48 [torch.Size([10, 20]), torch.Size([10, 1])]
^CTraceback (most recent call last):
  File "test.py", line 42, in <module>
    for idx, batch in enumerate(loader):
  File "/Users/ayushkarnawat/miniconda3/envs/tfrecord/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/Users/ayushkarnawat/miniconda3/envs/tfrecord/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/ayushkarnawat/miniconda3/envs/tfrecord/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch
    data.append(next(self.dataset_iter))
  File "/Users/ayushkarnawat/Documents/dev/python_workspace/tfrecord/tfrecord/iterator_utils.py", line 19, in sample_iterators
    yield next(iterators[choice])
  File "/Users/ayushkarnawat/Documents/dev/python_workspace/tfrecord/tfrecord/iterator_utils.py", line 8, in cycle
    for element in iterator_fn():
  File "/Users/ayushkarnawat/Documents/dev/python_workspace/tfrecord/tfrecord/reader.py", line 97, in tfrecord_loader
    if key not in example.features.feature:
KeyboardInterrupt
```

## Expected behavior
Since there are a total of 100 records between the two files, there should be exactly 10 batches each of size 10.

**Comment by vahidk** [comment]
This is intended behavior. MultiTFRecordDataset repeats each dataset to maintain the correct distribution. There's no other way to do it generally.
