### ISSUE TITLE
Map values to list 

### ISSUE THREAD

**Issue by ayushkarnawat** [vahidk/tfrecord#29]
Piggybacking off the comment "This is a breaking change. Let's not combine it with cleanup. It has to be made as a separate PR. Unless there's a use case for this I prefer to keep the old way."

_Originally posted by @vahidk in https://github.com/vahidk/tfrecord/pull/27_

For example, if the user inputs a value of type int (i.e. `"index": (5, "int")`) without enclosing it within `[]`, then the following error occurs:
 
```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    "index": (idx, "int")
  File "/Users/ayushkarnawat/Documents/dev/python_workspace/tfrecord/tfrecord/writer.py", line 41, in write
    record = TFRecordWriter.serialize_tf_example(datum)
  File "/Users/ayushkarnawat/Documents/dev/python_workspace/tfrecord/tfrecord/writer.py", line 83, in serialize_tf_example
    features = {key: serialize[dtype](value) for key, (value, dtype) in datum.items()}
  File "/Users/ayushkarnawat/Documents/dev/python_workspace/tfrecord/tfrecord/writer.py", line 83, in <dictcomp>
    features = {key: serialize[dtype](value) for key, (value, dtype) in datum.items()}
  File "/Users/ayushkarnawat/Documents/dev/python_workspace/tfrecord/tfrecord/writer.py", line 80, in <lambda>
    int64_list=example_pb2.Int64List(value=f))
TypeError: Value must be iterable
```

Obviously, the user can simply wrap their value within `[]`, but it shouldn't break code if that is not given.

**Comment by vahidk** [comment]
It is a breaking change e.g. the behavior for passing a tuple would change.

**Comment by ayushkarnawat** [comment]
I should have been more clear. Consider the scenario where the user inputs the following to insert into a tfrecord file:

```python
import numpy as np
import tfrecord

datum = {
    "image": (np.random.bytes(20), "byte"),
    "label": ([7.687], "float"),
    "index": (9, "int")
}
writer = tfrecord.TFRecordWriter("test.tfrecord")
writer.write(datum)
writer.close()
```

With the current implementation, we will get 

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    "index": (idx, "int")
  File "/Users/ayushkarnawat/Documents/dev/python_workspace/tfrecord/tfrecord/writer.py", line 41, in write
    record = TFRecordWriter.serialize_tf_example(datum)
  File "/Users/ayushkarnawat/Documents/dev/python_workspace/tfrecord/tfrecord/writer.py", line 83, in serialize_tf_example
    features = {key: serialize[dtype](value) for key, (value, dtype) in datum.items()}
  File "/Users/ayushkarnawat/Documents/dev/python_workspace/tfrecord/tfrecord/writer.py", line 83, in <dictcomp>
    features = {key: serialize[dtype](value) for key, (value, dtype) in datum.items()}
  File "/Users/ayushkarnawat/Documents/dev/python_workspace/tfrecord/tfrecord/writer.py", line 80, in <lambda>
    int64_list=example_pb2.Int64List(value=f))
TypeError: Value must be iterable
```

because the value `9` is not an iterable (i.e. `[9]`). Shouldn't the code still insert the datum properly into the tfrecord file since the index value of 9 is the correct type of "int"?

Within `TFRecordWriter.serialize_tf_example()`, all we have to do is check if the value (in this case `9` without the `[]`), is not of type `list, np.ndarray` and change it to be of type list, by setting the value as,

```python
if not isinstance(value, (list, np.ndarray)):
    value = [value]
```

This won't change/break the current behavior of passing in the tuple because the value will only be changed to a list if it not one. Hopefully, this is more clear!

**Comment by vahidk** [comment]
I said the behavior for passing a tuple would change. It can be fixed by also checking for a tuple. I think it should be fine to do if not isinstance(value, (list, tuple, np.ndarray)). I'll accept PR to make this change.

**Comment by vahidk** [comment]
Resolved: https://github.com/vahidk/tfrecord/pull/30/files
