### ISSUE TITLE
Can't create tfrecord, and load bytes in tfrecord not correct

### ISSUE THREAD

**Issue by Bigsealion** [vahidk/tfrecord#36]
I try to create tfrecord by following code, and I have pip the crc32c:
```
writer = tfrecord.TFRecordWriter(r"I:\testdata\patch_test2\a.tfrecord")
writer.write({
    "label": (1.4, "float")
})
```
But it return error for me:
```
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "D:\software\Anaconda3\envs\pt36\lib\site-packages\tfrecord\writer.py", line 45, in write
    self.file.write(TFRecordWriter.masked_crc(length_bytes))
  File "D:\software\Anaconda3\envs\pt36\lib\site-packages\tfrecord\writer.py", line 55, in masked_crc
    masked = np.uint32(masked)
OverflowError: Python int too large to convert to C long
```

So, I create tfrecord by tensorflow by following example
```
                example = tf.train.Example(features=tf.train.Features(feature={
                    "img_name": tf.train.Feature(bytes_list=tf.train.BytesList(value=[img_name.encode('utf-8')])),
                    'patch_name': tf.train.Feature(bytes_list=tf.train.BytesList(value=[patch_name.encode('utf-8')])),
                    'img_source_raw': tf.train.Feature(bytes_list=tf.train.BytesList(value=[img_source_raw])),
                    'img_mask_raw': tf.train.Feature(bytes_list=tf.train.BytesList(value=[img_mask_raw])),
                    'img_shape': tf.train.Feature(int64_list=tf.train.Int64List(value=shape))
                }))
                writer.write(example.SerializeToString())
```
but when I load this data by tfrecord, it return bad result for me:
```
loader = tfrecord.tfrecord_loader(p, None, {
    'label': 'int',
    'img_name': 'byte',
    'img_raw': 'byte',
    'img_shape': 'int'})

for record in loader:
    # print(record)
    print('img_shape:{}'.format(record['img_shape']))
    print('label:{}'.format(record['label']))
    print('img_name:{}'.format(record['img_name']))
```

print result like following:
```
img_shape:[62 86 75  3]
label:[1]
img_name:[112 114 101 112 114 111  99 101 115 115  95 112  97 100  95  85  78  69
  48  48  48  57  50  95  49 120  49 120  49  95  86  79  73  46 110 112
 121  95  49]
img_raw:[185 235  66 ...  15  39 190]
img_shape:[62 86 75  3]
```
the img_name become a numpy array rather than a bytes
So, I want to know how to create tfrecord by tfrecord and how to load bytes? Thanks!

**Comment by vahidk** [comment]
Try: writer.write({
    "label": ([1.4], "float")
})

And try:
print('img_name:{}'.format(record['img_name'].decode()))

**Comment by sailist** [comment]
```
import tfrecord

writer = tfrecord.TFRecordWriter("./data.tfrecord")
writer.write({
    "label": ([1.4], "float")
})
writer.close()
```

still have exception: `OverflowError: Python int too large to convert to C long`
