### ISSUE TITLE
Error related to parameter 'splits' in MultiTFRecordDataset 

### ISSUE THREAD

**Issue by CANVOLCANO** [vahidk/tfrecord#41]
Hi, I'm making experiments with pytorch on dataset  [Youtube8M](https://research.google.com/youtube8m/download.html).

My data preprocessing code is:
```python
    tfrecord_pattern = "/media/canvolcnao/新加卷/ML/Dataset/YT8M/test/{}.tfrecord"
    # index_pattern = "/path/to/{}.index"
    splits={}
    val_set_len=3844
    tem=''
    for i in range(val_set_len):
        splits['validate%(num)04d'%{'num':i}]=1/val_set_len
    description = {"labels": "byte", "video_id": "int","mean_rgb":"list","mean_audio":"list"}
    dataset = MultiTFRecordDataset(tfrecord_pattern, splits,description)
    loader = torch.utils.data.DataLoader(dataset, batch_size=32)
    data = next(iter(loader))
    print(data)
```

Howerver, a weird ERROR occured:
```
Traceback (most recent call last):
  File "/home/canvolcnao/ZCZ/SourceCode/VSCode/Python/ML/YT8M/SNR/dataPre.py", line 42, in <module>
    data = next(iter(loader))
  File "/home/canvolcnao/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 277, in __iter__
    return _SingleProcessDataLoaderIter(self)
  File "/home/canvolcnao/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 381, in __init__
    self._dataset_kind, self._dataset, self._auto_collation, self._collate_fn, self._drop_last)
  File "/home/canvolcnao/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 41, in create_fetcher
    return _utils.fetch._IterableDatasetFetcher(dataset, auto_collation, collate_fn, drop_last)
  File "/home/canvolcnao/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 21, in __init__
    self.dataset_iter = iter(dataset)
  File "/home/canvolcnao/anaconda3/lib/python3.7/site-packages/tfrecord/torch/dataset.py", line 129, in __iter__
    self.data_pattern, self.index_pattern, self.splits, self.description)
  File "/home/canvolcnao/anaconda3/lib/python3.7/site-packages/tfrecord/reader.py", line 215, in multi_tfrecord_loader
    for split in splits.keys()]
  File "/home/canvolcnao/anaconda3/lib/python3.7/site-packages/tfrecord/reader.py", line 215, in <listcomp>
    for split in splits.keys()]
AttributeError: 'dict' object has no attribute 'format'
```

I can't figure out, since it doesn't seem that there is an 'dict' object invoking its 'format' attribute?

**Comment by vahidk** [comment]
there's no type list. providing the description is optional. It's used for verification. Try passing None as description.
