### ISSUE TITLE
error in example

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [vahidk/tfrecord#49]
Hello,
Thanks for the library. I am following example exactly from readme.

```python
import tfrecord
path = '/tmp/xyz.tfrecord'
writer = tfrecord.TFRecordWriter(path)
writer.write({'length': (3, 'int'), 'label': (1, 'int')},
           {'tokens': [[0, 0, 1], [0, 1, 0], [1, 0, 0]], 'seq_labels': [0, 1, 1]})
writer.write({'length': (3, 'int'), 'label': (1, 'int')},
           {'tokens': [[0, 0, 1], [1, 0, 0]], 'seq_labels': [0, 1]})
writer.close()

import tfrecord

context_description = {"length": "int", "label": "int"}
sequence_description = {"tokens": "int ", "seq_labels": "int"}
loader = tfrecord.tfrecord_loader(path, None,
                                context_description,
                                sequence_description=sequence_description)

for context, sequence_feats in loader:
    print(context["label"])
    print(sequence_feats["seq_labels"])
```

but I had the following error
```
Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "/home/chen/anaconda3/envs/learning_to_simulate/lib/python3.7/site-packages/tfrecord/writer.py", line 55, in write
    record = TFRecordWriter.serialize_tf_sequence_example(datum, sequence_datum)
  File "/home/chen/anaconda3/envs/learning_to_simulate/lib/python3.7/site-packages/tfrecord/writer.py", line 148, in serialize_tf_sequence_example
    features = {key: serialize_repeated(value, dtype) for key, (value, dtype) in features_datum.items()}
  File "/home/chen/anaconda3/envs/learning_to_simulate/lib/python3.7/site-packages/tfrecord/writer.py", line 148, in <dictcomp>
    features = {key: serialize_repeated(value, dtype) for key, (value, dtype) in features_datum.items()}
ValueError: too many values to unpack (expected 2)
```

Would you like to take a look at this? Many thanks!

**Comment by Chen-Cai-OSU** [comment]
All right, I figure this out myself. You may want to update the example accordingly. (add type for the sequence_datum.)
```python
import tfrecord
path = '/tmp/xyz.tfrecord'
writer = tfrecord.TFRecordWriter(path)
writer.write({'length': (3, 'int'), 'label': (1, 'int')},
             {'tokens': ([[0, 0, 1], [0, 1, 0], [1, 0, 0]], 'float'), 'seq_labels': ([0, 1, 1], 'float')}) # changed
writer.write({'length': (3, 'int'), 'label': (1, 'int')},
             {'tokens': ([[0, 0, 1], [1, 0, 0]], 'float'), 'seq_labels': ([0, 1], 'float')})
writer.close()

import tfrecord

context_description = {"length": "int", "label": "int"}
sequence_description = {"tokens": "float", "seq_labels": "float"}
loader = tfrecord.tfrecord_loader(path, None,
                                  context_description,
                                  sequence_description=sequence_description)

for context, sequence_feats in loader:
    print(context["label"])
    print(sequence_feats["tokens"])
```

**Comment by vahidk** [comment]
Thank you will fix!
