### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by mmhnoaccount** [vahidk/tfrecord#54]
```
import tfrecord

writer = tfrecord.TFRecordWriter("E:/File/package_by_mmh/train_set_128/train.tfrecord")
writer.write({'length': (3, 'int'), 'label': (1, 'int')},
             {'tokens': ([[0, 0, 1], [0, 1, 0], [1, 0, 0]], 'int'), 'seq_labels': ([0, 1, 1], 'int')})
writer.write({'length': (3, 'int'), 'label': (1, 'int')},
             {'tokens': ([[0, 0, 1], [1, 0, 0]], 'int'), 'seq_labels': ([0, 1], 'int')})
writer.close()
```

when using above example, some errors occur.

```
Traceback (most recent call last):
  File "E:/File/package_by_mmh/DeepChroma/testTFrcord.py", line 4, in <module>
    writer.write({'length': (3, 'int'), 'label': (1, 'int')},
  File "E:\Anaconda3\lib\site-packages\tfrecord\writer.py", line 60, in write
    self.file.write(TFRecordWriter.masked_crc(length_bytes))
  File "E:\Anaconda3\lib\site-packages\tfrecord\writer.py", line 70, in masked_crc
    masked = np.uint32(masked)
OverflowError: Python int too large to convert to C long
```

**Comment by vahidk** [comment]
Hmmm. I can't reproduce this. Works fine on my linux machine.
You can try updating the code to:
masked = np.uint32(masked & np.iinfo(np.uint32).max)
