### ISSUE TITLE
Error in consuming a tfrecords

### ISSUE THREAD

**Issue by nkundiushuti** [vahidk/tfrecord#88]
I am consuming a multitfrecords object and after a few iterations, I reach this error
Epoch: 1/50
Epoch 0, Avg Loss: 0.01: : 13it [00:02,  4.46it/s] 
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    main(arg_dic)
  File "train.py", line 144, in main
    approach.train()
  File "/home/marius/code/separation_denoising/approaches/supervised_teacher_denoising.py", line 80, in train
    self.train_epoch()
  File "/home/marius/code/separation_denoising/approaches/supervised_teacher_denoising.py", line 100, in train_epoch
    for cnt, input in enumerate(train_tqdm_gen):
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
OverflowError: Caught OverflowError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/marius/code/separation_denoising/datasets/supervised_denoising_dataset.py", line 27, in __iter__
    for source, noise in zip(self.iterator["source"],self.iterator["noise"]):
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/tfrecord/iterator_utils.py", line 50, in sample_iterators
    yield next(iterators[choice])
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/tfrecord/iterator_utils.py", line 14, in cycle
    for element in iterator_fn():
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/tfrecord/reader.py", line 219, in example_loader
    for record in record_iterator:
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/tfrecord/reader.py", line 80, in tfrecord_iterator
    yield from read_records()
  File "/home/marius/miniconda3/envs/torch-py38/lib/python3.8/site-packages/tfrecord/reader.py", line 71, in read_records
    datum_bytes = datum_bytes.zfill(int(length * 1.5))
**OverflowError: Python int too large to convert to C ssize_t**

**Comment by noahzhy** [comment]
same problem, did you figure it out?
